(() => {
  const money = value => { if (String(value || '').toUpperCase() === 'BANK') return 'BANK'; const amount = Number(value); return Number.isFinite(amount) ? amount.toLocaleString('en-US') : '0'; };
  const platformName = value => { const name = String(value || 'unknown').toLowerCase(); return ['twitch', 'youtube', 'kick'].includes(name) ? name : 'unknown'; };
  function playerRow(player) { const row = document.createElement('div'); row.className = 'hl-players-player'; const name = document.createElement('span'); name.className = 'hl-players-name'; name.textContent = player.name || ''; const vote = String(player.vote || '').toLowerCase(); const platform = platformName(player.platform); const icon = document.createElement('span'); icon.className = 'hl-players-vote hl-players-vote-platform-' + platform + (vote === 'higher' || vote === 'lower' ? ' hl-players-vote-' + vote : ''); icon.title = vote === 'higher' ? 'Higher' : vote === 'lower' ? 'Lower' : 'Waiting'; const bet = document.createElement('span'); bet.className = 'hl-players-bet'; bet.textContent = vote ? money(player.bet) : 'Waiting'; row.append(name, icon, bet); return row; }
  function build(panel) { panel.setContent('<section class="hl-players"><div class="hl-players-heading"><span>Players</span><span class="hl-players-count">0/0</span></div><div class="hl-players-list"></div></section>'); return panel.element.querySelector('.hl-players'); }
  function applyAppearance(panel, appearance = {}) {
    const root = panel.element.querySelector('.hl-players') || build(panel), value = appearance.players || {};
    const angle = ((Number(value.gradientDirection) || 0) + 90) % 360, color1 = value.color1 || '#20252a', color2 = value.color2 || '#20252a';
    const borderWidth = Number.isFinite(Number(value.borderWidth)) ? Number(value.borderWidth) : 4, borderColor = value.borderColor || '#0384CB';
    const radius = Number.isFinite(Number(value.cornerRadius)) ? Number(value.cornerRadius) : 12, title = value.title || {}, titleShadow = title.shadowDirection || {};
    const shadowAngle = Number(titleShadow.angle) || 0, shadowDistance = Math.max(0, Number(titleShadow.distance) || 0), radians = shadowAngle * Math.PI / 180;
    root.style.setProperty('--hl-players-color-1', color1); root.style.setProperty('--hl-players-color-2', color2); root.style.setProperty('--hl-players-gradient-direction', angle + 'deg'); root.style.setProperty('--hl-players-border-width', borderWidth + 'px'); root.style.setProperty('--hl-players-border-color', borderColor); root.style.setProperty('--hl-players-radius', radius + 'px'); root.style.setProperty('--hl-players-title-color', title.color || '#ffffff'); root.style.setProperty('--hl-players-title-shadow-color', title.shadowColor || '#000000'); root.style.setProperty('--hl-players-title-shadow-x', Math.sin(radians) * shadowDistance + 'px'); root.style.setProperty('--hl-players-title-shadow-y', -Math.cos(radians) * shadowDistance + 'px');
    return root;
  }
  function update(panel, state = {}) { const root = panel.element.querySelector('.hl-players') || build(panel), list = root.querySelector('.hl-players-list'), count = root.querySelector('.hl-players-count'), players = Array.isArray(state.players) ? state.players : [], started = Number(state.startedPlayers) || players.length; if (count) count.textContent = players.length + '/' + started; list.replaceChildren(); players.forEach(player => list.appendChild(playerRow(player))); return root; }
  window.RTSHigherLowerPlayers = { build, update, applyAppearance };
})();
